### ISSUE TITLE
jsonb_pretty method buffer ending prematurely

### ISSUE THREAD

**Issue by Jl14Salvador** [dbcli/pgcli#1077]
## Description
When the postgres method `jsonb_pretty` is used on a jsonb object that is larger than ~15-20 lines, then the result is cut off. Not sure if it is cut off from a certain number of characters or certain number of lines.
i.e.
```
test@localhost:main>  select jsonb_pretty(object) from table;
+-------------------------------------------------------------------+
| jsonb_pretty                                                      |
|-------------------------------------------------------------------|
| [                                                                 |
|     {                                                             |
|         "sample": "1",                                            |
|         "this": {                                                 |
|             "does": true,                                         |
|             "not": null,                                          |
|             "output": null,                                       |
|             "properly": null,                                     |
|             "and": null,                                          |
|             "is": null,                                           |
|             "cut": null                                           |
|         },                                                        |
|         "off": "false",                                           |
|         "prematurely": false,                                     |
|         "unfortunately": true                                     |
+-------------------------------------------------------------------+

```
## Your environment
Connected to a local postgres database

- [ ] Please provide your OS and version information.
Running Mac OS 10.14.5

- [ ] Please provide your CLI version.
pgcli version 2.1.1 (latest)

- [ ] What is the output of ``pip freeze`` command.
No output.

To be clear, this issue does **_not_** happen when using the native psql cli tool for postgres.

**Comment by CubixSystem** [comment]
I think it's not `jsonb_pretty` issue, you can reproduce it using only `select`
```sql
select (jsonb_field_with_big_json) from your_table
```

**Comment by Jl14Salvador** [comment]
@CubixSystem Yes, after further use, I can also confirm this. Even a simple `\sf function_name` will cut off printing an entire function definition. It ends prematurely after a similar amount of characters that are outputted.  It seems that the method to print out pretty values in pgcli is limiting the amount of characters it outputs. 
``` sql

+------------------------------------------------------------+
| source                                                     |
|------------------------------------------------------------|
| CREATE OR REPLACE FUNCTION public.build_object()  |
|  RETURNS jsonb                                             |
|  LANGUAGE sql                                              |
| AS $function$                                              |
|   select jsonb_build_object(                               |
|     'item_1', jsonb_build_object('type', 'string'),        |
|     'item_2', jsonb_build_object('type', 'string'),        |
|     'item_3', jsonb_build_object('type', 'string'),        |
|     'item_4', jsonb_build_object('type', 'string'),        |
|     'item_5', jsonb_build_object('type', 'string'),        |
|     'item_6', jsonb_build_object('type', 'string'),        |
|     'item_7', jsonb_build_object('typ                      |  -- this just stop printing mid-function and ends
+------------------------------------------------------------+
```

**Comment by amjith** [comment]
Can you try upgrading `cli_helpers`? 
```
pip install -U cli_helpers
```

`cli_helpers` is a dependency we use to print tabulated output and we made some choices that started truncating the output prematurely. It is now fixed and we have released a new version.

**Comment by Jl14Salvador** [comment]
@amjith  I tried upgraded it but it hasn't solved the issue. 
``` 
~ : pip list
Package        Version
-------------- -------
cli-helpers    1.2.1
configobj      5.0.6
pip            19.1.1
setuptools     28.8.0
six            1.12.0
tabulate       0.8.3
terminaltables 3.1.0
wcwidth        0.1.7
```

Running the latest version 1.2.1.

**Comment by amjith** [comment]
I have a suspicion that pgcli is still using the old version of cli_helpers. The latest version of cli_helpers adds an ellipsis when it truncates the output which I don't see in your output. 

Can you try uninstalling pgcli and reinstalling it? 

```
pip uninstall pgcli
```

and then ensure that pgcli is gone by trying to launch pgcli. Sometimes you might have another pgcli installed via brew or apt or something.

```
pip install pgcli
```

**Comment by Jl14Salvador** [comment]
I actually had it installed through `brew` and it looks like the formula had not been updated yet. And when i uninstalled and reinstalled it the issue persisted. I then uninstalled it using `brew` and reinstalled it through `pip` instead and that installed the latest version with that fix you mentioned (from `cli-helper 1.2.1`). Thanks for your help! @amjith 🎉

**Comment by Globegitter** [comment]
Strange, I am running on the latest pgcli and cli-helpers installed through pip3, on Ubuntu 19.04 and running into a very similar issue, where my whole table is just going beyond the screen when trying to print a large jsonb column. Interestingely enough `jsonb_pretty` doesn't change anything about the format of the result. Any idea what the issue could be?

**Comment by Globegitter** [comment]
If I use the normal `psql` client btw it can print the column just fine.
