### ISSUE TITLE
quitting less is also closing pgcli

### ISSUE THREAD

**Issue by Notaduck** [dbcli/pgcli#1132]
## Description
As the title of the issue states quitting less is also closing pgcli.

A simple query like this opens up `less`

```
select G.d_ID, avg(G.g_Price) as g_AvgPrice
 from gGarments G
 group by G.d_ID
```

When `q` is pressed to close `less` pgcli is also closed and there is nor foreground jobs running

## Your environment

- [ ] 5.3.15-1-MANJARO
- [ ] pgcli Version: 2.2.0
- [ ] (pip freeze](https://termbin.com/egx5)
- [ ] `zsh 5.7.1 (x86_64-pc-linux-gnu)`

**Comment by notaduck** [comment]
Seems like this has been fixed v.2.2.0

**Comment by notaduck** [comment]
The issue is still there, I was mistaken.
The odd thing is that this only happens for this single query, every other query which displays the results in less does not close down the entire application.

**Comment by catherinedevlin** [comment]
Though I don't have  your particular table, I can't duplicate this in pgcli 3.0.0.

**Comment by notaduck** [comment]
I think we can close this issue for now, I can't replicate it anymore either :)

**Comment by mattadams** [comment]
I am still getting this with pgcli 3.2.0 on FreeBSD 13. If I use "q" to quit less before scrolling to the bottom of the pagnated display it also quits pgcli before I have a chance to do anything else.

**Comment by vtronko** [comment]
Still getting this, unfortunately.

**Comment by dbaty** [comment]
I cannot reproduce this with the latest version of pgcli (4.0.1), with less 633 under Fedora 38. Here is a screencast: 

[![asciicast](https://asciinema.org/a/621157.svg)](https://asciinema.org/a/621157)

Can anyone reproduce with the latest pgcli? If so, what is your operating system and version of less?

**Comment by j-bennet** [comment]
Also, what's your `LESS` env var set to?

**Comment by mattadams** [comment]
I don't believe this is happening anymore for me. Also using 4.0.1. My LESS env is `LESS=-SRXF`.
